# Generated by Django 2.2.4 on 2019-08-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20190827_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/profile_pics/commerce_logo.png', upload_to='profile_pics'),
        ),
    ]
