# Generated by Django 2.2.4 on 2019-08-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_auto_20190828_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='userforms/media/profile_pics'),
        ),
    ]
