# Generated by Django 2.2.1 on 2019-08-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
