# Generated by Django 2.2.1 on 2019-08-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0014_note_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='content',
        ),
    ]
