# Generated by Django 2.2.1 on 2019-08-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0015_remove_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
